# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: 
          name: "say hello"
          command: "echo Hello, world!"
  run-tests:
    docker:
      - image: cimg/base:stable
    working_directory: ~/server/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          name: "Run tests"
          command: |
            npm install
            npm test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - run-tests
      - say-hello